const faqs = [
    { question: 'What is conveyancing?', answer: 'Conveyancing is a legal process that involves the transfer of property ownership from one party to another. It typically includes all the legal and administrative work required to ensure that the transfer is valid and legally binding.' },
    { question: 'What is the process of conveyancing in Sydney?', answer: "In Sydney, conveyancing typically begins with offer acceptance and due diligence. This involves legal document review, property searches, and verification of the seller's rights. The conveyancer drafts the sales contract, negotiates amendments, and ensures legal compliance. The process concludes with contract exchange, settlement, and property ownership transfer to the buyer." },
    { question: 'Why do I need conveyancing?', answer: "Conveyancing is essential for several reasons. Firstly, it ensures that the property transfer process is legally valid and binding, providing security and peace of mind for both buyers and sellers. Additionally, conveyancers handle complex legal documentation, ensuring that all necessary paperwork is completed accurately and in compliance with relevant laws and regulations." },
    { question: 'How long should a conveyancer in Sydney take to complete the entire process?', answer: "The duration of the conveyancing process in Sydney can vary depending on various factors such as the complexity of the transaction, the responsiveness of involved parties, and any unforeseen issues that may arise. Generally, the process typically takes between 4 to 6 weeks from the acceptance of an offer to settlement." },
    { question: 'How much should I expect to pay for conveyancing services in Sydney?', answer: "The cost of conveyancing services in Sydney can vary depending on several factors, including the complexity of the transaction, the value of the property, and the fees charged by individual conveyancers or law firms. Generally, conveyancing fees in Sydney range from around $800 to $2,500 or more, excluding additional expenses such as government fees, property searches, and disbursements." },
    { question: 'What information does a Sydney conveyancer need?', answer: "A Sydney conveyancer typically needs property details, seller and buyer information, the sales contract, financial details, and identification documents from both parties. They also require copies of the property title deed, survey plans, and information about any outstanding debts or liabilities. Any special conditions or requirements should also be communicated to the conveyancer for a smooth process." },
    { question: 'Who is a good conveyancer in Sydney?', answer: "Love Home Conveyancing is a reputable choice for conveyancing services in Sydney, known for their expertise, efficiency, and personalized approach. With a track record of successful transactions and satisfied clients, Love Home Conveyancing offers reliable and professional service to ensure a smooth property transfer process." },
  ];
